export const API_URL = "https://inventory-management-system-e36a.onrender.com";

export const actionTypes = {
    ADD_INVENTORY_DATA_SUCCESS: 'ADD_INVENTORY_DATA_SUCCESS',
    DELETE_INVENTORY_DATA_SUCCESS: 'DELETE_INVENTORY_DATA_SUCCESS',
    UPDATE_INVENTORY_DATA_SUCCESS: 'UPDATE_INVENTORY_DATA_SUCCESS',
    GET_INVENTORY_DATA_SUCCESS: 'GET_INVENTORY_DATA_SUCCESS',
    ADD_INVENTORY_DATA_ERROR: 'ADD_INVENTORY_DATA_ERROR',
    DELETE_INVENTORY_DATA_ERROR: 'DELETE_INVENTORY_DATA_ERROR',
    UPDATE_INVENTORY_DATA_ERROR: 'UPDATE_INVENTORY_DATA_ERROR',
    GET_INVENTORY_DATA_ERROR: 'GET_INVENTORY_DATA_ERROR',
    ADD_SALES_DATA_SUCCESS: 'ADD_SALES_DATA_SUCCESS',
    DELETE_SALES_DATA_SUCCESS: 'DELETE_SALES_DATA_SUCCESS',
    UPDATE_SALES_DATA_SUCCESS: 'UPDATE_SALES_DATA_SUCCESS',
    GET_SALES_DATA_SUCCESS: 'GET_SALES_DATA_SUCCESS',
    ADD_SALES_DATA_ERROR: 'ADD_SALES_DATA_ERROR',
    DELETE_SALES_DATA_ERROR: 'DELETE_SALES_DATA_ERROR',
    UPDATE_SALES_DATA_ERROR: 'UPDATE_SALES_DATA_ERROR',
    GET_SALES_DATA_ERROR: 'GET_SALES_DATA_ERROR',
    DATA_LOADING: "DATA_LOADING",
  }